# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='year',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
